/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.Vprojects();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Vprojects', function() {
    it('should create an instance of Vprojects', function() {
      // uncomment below and update the code to test Vprojects
      //var instane = new TempApi.Vprojects();
      //expect(instance).to.be.a(TempApi.Vprojects);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.Vprojects();
      //expect(instance).to.be();
    });

    it('should have the property prName (base name: "prName")', function() {
      // uncomment below and update the code to test the property prName
      //var instance = new TempApi.Vprojects();
      //expect(instance).to.be();
    });

    it('should have the property prSDate (base name: "prSDate")', function() {
      // uncomment below and update the code to test the property prSDate
      //var instance = new TempApi.Vprojects();
      //expect(instance).to.be();
    });

    it('should have the property prEDate (base name: "prEDate")', function() {
      // uncomment below and update the code to test the property prEDate
      //var instance = new TempApi.Vprojects();
      //expect(instance).to.be();
    });

    it('should have the property prFunding (base name: "prFunding")', function() {
      // uncomment below and update the code to test the property prFunding
      //var instance = new TempApi.Vprojects();
      //expect(instance).to.be();
    });

  });

}));
